# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160506_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='provider',
            field=models.IntegerField(choices=[(1, 'OOREDO'), (2, 'XL'), (3, 'TELKOMSEL'), (4, 'Three')]),
        ),
    ]
