# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
