# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='is_online',
            field=models.IntegerField(choices=[(1, 'Online'), (2, 'Offline')], default=2),
        ),
    ]
