# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160524_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='type',
            field=models.IntegerField(default=2),
        ),
    ]
