# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('user2', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'Order Pulsa'), (2, 'Cairkan Dana')])),
                ('total', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField()),
                ('user2', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'Order Pulsa'), (2, 'Cairkan Dana')])),
                ('total', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
