# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20160531_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionorder',
            name='order',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
