# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Waiting'), (3, 'Done')], default=1),
        ),
    ]
