# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_counter_type'),
        ('order', '0003_auto_20160530_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='counter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Counter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer'),
        ),
    ]
